---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: presto
    run_list:
        - recipe[generic::create_environment]
        - recipe[presto::setup_or_update]
        - recipe[presto::start]
    attributes: { "opsworks": { "instance": {"hostname": "presto1", "id": "id-4554"}, "layers": {"presto": {"instances": {"presto1": {"elastic_ip": "127.0.0.1"}}}} }, "deploy": {"presto": {"database": {"host": "127.0.0.1", "username": "buremba", "password": "", "database": ""}}}}
  - name: rakam
    run_list:
        - recipe[generic::create_environment]
        - recipe[rakam::setup_or_update]
        - recipe[rakam::start]
    attributes: { "opsworks": { "instance": {"hostname": "rakam1", "id": "id-4554"}, "layers": {"presto": {"instances": {"presto1": {"elastic_ip": "127.0.0.1"}}}} }, "deploy": {"rakam": {"database": {"host": "127.0.0.1", "username": "buremba", "password": "", "database": ""}}}}
