---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  cookbook_files_glob: "**/*"

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[generic::install_java]
    attributes:
