source "https://supermarket.chef.io"

cookbook 'build-essential', '= 3.2.0'
cookbook 'windows', '= 1.44.3'
cookbook 'homebrew', '= 2.1.2'
cookbook 'ohai', '= 3.0.1'
cookbook 'yum-epel', '= 0.7.1'
cookbook 'yum-repoforge', '~> 1.0.0'
cookbook 'java', '~> 1.36.0'
cookbook 'nodejs', '~> 2.4.4'
cookbook 'ark', '~> 0.9.0'
cookbook 'apt', '= 3.0.0'
cookbook 'yum', '= 3.13.0'
cookbook 'generic', path: './generic'
cookbook 'rakam', path: './rakam'
cookbook 'presto', path: './presto'
