name             'rakam'
maintainer       'Burak Emre Kabakcı'
maintainer_email 'emrekabakci@gmail.com'
license          'All rights reserved'
description      'Installs/Configures rakam'
long_description 'Installs/Configures rakam'
version          '0.1.0'
