default['environment'] = 'production'
default['presto_version'] = '0.190'
default['rakam_presto_streaming_version'] = ''
default['rakam_presto_raptor_version'] = ''
default['jvm-properties'] = ''

default['s3']['streaming'] = 'rakam-streaming'
default['s3']['bulk'] = 'rakam-bulk'
default['s3']['batch'] = 'rakam-batch'
default['kinesis'] = 'rakam-stream'
default['chef_client']['ca_cert_path'] = '/etc/ssl/certs/ca-bundle.crt'
