default['environment'] = 'production'
default['presto_version'] = '0.173'
default['data-dir'] = '/mnt/presto'
default['rakam_presto_streaming_version'] = ''
default['rakam_presto_raptor_version'] = ''
default['jvm-properties'] = ''

default['s3']['streaming'] = 'rakam-streaming'
default['s3']['bulk'] = 'rakam-bulk'
default['s3']['batch'] = 'rakam-batch'
default['kinesis'] = 'rakam-stream'
